spring:
  application:
    name: Cash Store Application
  datasource:
    url: jdbc:postgresql://localhost:5432/cash_store
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  main:
    web-application-type: none

  jpa:
    hibernate:
      ddl-auto: validate    # или validate, create, create-drop
    show-sql: true

logging:
  file:
    name: logs/cash-app.log
  charset:
    console: UTF-8
  logback:
    rollingpolicy:
      max-file-size: 80MB
      total-size-cap: 200MB
      max-history: 1
      file-name-pattern: logs/cash-app.%d{yyyy-MM-dd}-%i.log
#  level:
#    org.hibernate.SQL: DEBUG            # сами SQL
#    org.hibernate.orm.jdbc.bind: TRACE  # значения параметров (binding)
#    org.hibernate.orm.jdbc.extract: TRACE  # (опц.) извлечение из ResultSet

app:
  http:
    enable-timeout: true   # отключить таймауты -> false
    connect-timeout: 10s
    read-timeout: 30s
  product:
    universal-product-barcode: universal-product-200001
    product-return-period: 14

