spring:
  application:
    name: Yeleup Cash Store Application
  datasource:
    url: jdbc:postgresql://localhost:5432/cash_store
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate    # или validate, create, create-drop
    show-sql: true

logging:
  charset:
    console: UTF-8

app:
  http:
    enable-timeout: true   # отключить таймауты -> false
    connect-timeout: 10s   # формат Duration: 500ms, 5s, 1m
    read-timeout: 30s
  product:
    universal-product-barcode: universal-product-200001
    organization-name: ${ORGANIZATION_NAME}
    cashier-name: ${CASHIER_NAME}
    product-return-period: 14

api:
  url-basic:
    category1c:
      base-url: ${API_CATEGORIES_URL}
      username: ${API_USERNAME}
      password: ${API_PASSWORD}
    product1c:
      base-url: ${API_PRODUCTS_URL}
      username: ${API_USERNAME}
      password: ${API_PASSWORD}

